version: "3.8"

services:
    db:
        container_name: db
        image: mysql:5.7
        volumes:
            - db-data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${NAMEDB}
            MYSQL_USER: ${USERDB}
            MYSQL_PASSWORD: ${PASSDB}
        ports:
            - "3306"

    app:
        depends_on:
            - db
        container_name: app
        ports: 
            - "9000:9000"
        build: .

    godoc:
        container_name: godoc
        ports:
            - "6060:6060"
        build: 
            context: .
            dockerfile: ./godoc/Dockerfile

volumes:
    db-data:
        